### PR TITLE
add svg animation using css into svganimationusingcss

### PR DESCRIPTION
**Pull request by InsAneDark**
pls review my PR.

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
Hey it seems you have only added the div not the full html page

**Comment by InsAneDark** [comment]
no its full code of that html page ....
in html5 there is no need of <html> open and closed tag </html>
because it's not case sensitive....
ok i just gonna edit it

**Comment by InsAneDark** [comment]
now pls review my PR.

**Comment by DiptoChakrabarty** [comment]
Can you tell me how can I see the animation , I might be following the wrong steps but my browser just shows an empty
 white page  or you could add an image of the animation in the same directory  README.md

**Pull request closed without merging**
